# -*- coding: utf-8 -*-
"""PDFChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWTpzwJ8LC5x7hxMKKUBqcrVV2eGMq2X
"""

!pip install -q --upgrade langchain langchain_google_genai langchain-core langchain_community docs2txt pydf langchain_chroma sentence_transformers

"""**LangChain Components and Expression Language (LCEL)**
1. LLM
2. Output Parser
3. Structured Output
4. Prompt Templates
5. LLM Messages
"""

import os

os.environ["GOOGLE_API_KEY"] = "AIzaSyBfGiNUJ3RWKMAtbU8g7DW46xiKLqokWDY"

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"] = "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"
os.environ["LANGCHAIN_PROJECT"] = "rag-chatbot"

# LLM using LangChain

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model = "gemini-1.5-flash")
llm_response = llm.invoke("Tell me a joke about coding")
llm_response

from langchain_core.output_parsers import StrOutputParser  # this is used to get a cleaner output

output_parser = StrOutputParser()
output_parser.invoke(llm_response)

# creating a Chain

chain = llm | output_parser
chain.invoke("Tell me a joke about coding")

from typing import List
from pydantic import BaseModel, Field

class Fone(BaseModel):
    summary: str = Field(description="Brief summary of review")
    duration: float = Field(description="average duration of a race")
    pros: List[str] = Field(description="List of positive aspects")

prompt_text = '''
Formula 1 (F1) is a premier global motorsport where teams, called *constructors*, design and build high-performance, open-wheel, single-seater race cars to compete in a series of events known as the **F1 World Championship**. Each season consists of multiple *Grands Prix* held on purpose-built circuits and city streets across different countries, testing drivers’ skill and teams’ engineering innovation.

Cars are powered by advanced hybrid engines combining a turbocharged internal combustion engine with energy recovery systems (ERS) for extra power and efficiency. Races typically last around 1.5 to 2 hours, with strategy playing a huge role—teams must manage tire compounds, fuel use, and pit stops while adapting to weather, track conditions, and safety car periods.

F1 is not just about speed—it’s a mix of precision driving, split-second decision-making, and cutting-edge technology. Championships are awarded in two categories: **Drivers’ Championship** for the best driver and **Constructors’ Championship** for the most successful team. The sport pushes the limits of human and machine performance, attracting millions of fans worldwide.
'''

structured_llm = llm.with_structured_output(Fone)
output = structured_llm.invoke(prompt_text)
print(output)
# print(output.summary)
print(output.duration)
# print(output.pros)

from langchain_core.prompts import ChatPromptTemplate     # using a dyamic prompt

prompt = ChatPromptTemplate.from_template("Tell me a joke about {topic}")

prompt.invoke({"topic": "sports"})

chain2 = prompt | llm | output_parser
result = chain2.invoke({"topic": "sports"})
print(result)

from langchain_core.messages import HumanMessage, SystemMessage
messages = [
    SystemMessage(content="You are a helpful coding assistant!"),
    HumanMessage(content="tell me a joke about sports")
]
result2 = llm.invoke(messages)
print(result2)

prompt2 = ChatPromptTemplate([
    ("system", "You are a helpful coding assistant!"),
    ("human", "tell me a joke about {topic}")
])
chain3 = prompt2 | llm
result3 = chain3.invoke({"topic": "sports"})
print(result3)

"""**Document Processing**

1. Loading Documents
2. Splitting Documents
"""

!pip install Docx2txt

from langchain_community.document_loaders import PyPDFLoader, Docx2txtLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from typing import List
from langchain_core.documents import Document
import os

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 1000, chunk_overlap = 200, length_function = len)
docx_loader = Docx2txtLoader("/content/docs/Mrunal-resume.docx")
document = docx_loader.load()

splits = text_splitter.split_documents(document)
print(f"splitted with {len(splits)} chunks")
print(len(document))

!pip install pypdf

def load_documents(folder_path : str)-> List[Document]:
  documents = []
  for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    if filename.endswith('.pdf'):
      loader = PyPDFLoader(file_path)
    elif filename.endswith('.docx'):
      loader = Docx2txtLoader(file_path)
    else:
      print(f"unsupported file type: {filename}")
      continue
    documents.extend(loader.load())
  return documents

folder_path = "/content/docs"
docs = load_documents(folder_path)
print(f"loaded {len(docs)} from docs folder")

splits = text_splitter.split_documents(docs)
print(f"splitted documents into {len(splits)} chunks")

"""**Creating Embeddings**

1. using GoogleAI Embeddings
2. using SentenceTranformer
"""

from langchain_google_genai import GoogleGenerativeAIEmbeddings

embedding = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
document_embedding = embedding.embed_documents([split.page_content for split in splits])
print(f"created embedding for {len(document_embedding)} document chunks")

"""**setting up the vector store**

1. Creating the vector store
2. performing similarity search
3. creating Retriever
"""

from langchain_chroma import Chroma

embedding_function = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

vectorstore = Chroma.from_documents(
    collection_name = "my_collection",
    documents = splits,
    embedding = embedding_function,
    persist_directory = "./chroma_db")

query = "whats is the resume projects?"

search_results = vectorstore.similarity_search(query)
print(f"\n Top 2 most relevant search for the query : '{query}' \n")

for i,result in enumerate(search_results,1):
  print(f"result {i}:")
  print(f"source: {result.metadata.get('source','unknown')}")
  print(f"content: {result.page_content}")

#Creating retriever

retriever = vectorstore.as_retriever(search_kwargs = {"k": 2})
retriever_result = retriever.invoke("what is the name of the candidate in resume")
print(retriever_result)

from langchain_core.prompts import PromptTemplate
from langchain.schema.runnable import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
template = """
Answer the question based only on the following context:
{context}

Question: {question}
Answer: """

prompt = PromptTemplate.from_template(template)
def docs2str(docs):
  return "\n\n".join(doc.page_content for doc in docs)

rag_chain = (
    {"context":retriever | docs2str, "question":RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

question = "what is the education of a person?"
response = rag_chain.invoke(question)
print(question)
print(response)

from decimal import Context
from langchain_core.prompts import MessagesPlaceholder
from langchain.chains import create_history_aware_retriever
from langchain.chains.combine_documents import create_stuff_documents_chain

context_prompt = """
Given a chat history and latest user question which might

"""
context_q_system_prompt = ChatPromptTemplate.from_messages([
    ("system", context_prompt),
    MessagesPlaceholder("chat_history"),
    ("human","{input}")
])

context_chain = context_q_system_prompt | llm | StrOutputParser()
print(context_chain.invoke({"input": "what is the cgpa of a person?","chat_history":[]}))

from langchain.chains import create_retrieval_chain

history = create_history_aware_retriever(
    llm,retriever,context_q_system_prompt
)

qa_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant"),
    ("system","Context:{context}"),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human","{input}")
])

question_answer_chain = create_stuff_documents_chain(llm,qa_prompt)
rag_chain = create_retrieval_chain(history,question_answer_chain)

from langchain_core.messages import HumanMessage,AIMessage

chat_history = []
question1 = "where was his college?"